### ISSUE TITLE
SERVICE_ID = "ivo://oats.inaf.it/cred" should be configurable

### ISSUE THREAD

**Issue by bertocco** [opencadc/cdp#6]
In file 
cdp/cadc-cdp/src/main/java/ca/nrc/cadc/cred/client/Main.java
SERVICE_ID = "ivo://oats.inaf.it/cred" should be configurable

Proposed patch: to add a constructor to initialize the string and add the string initialiaztion to the main method also:

  //public static final String SERVICE_ID = "ivo://oats.inaf.it/cred";
    public static String SERVICE_ID;

```
public Main() {
    LocalAuthority localAuthority = new LocalAuthority();       
    URI serviceURI = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());
    SERVICE_ID = serviceURI.toString();


}

/**
 * Main class for accessing CDP
 * 
 * @param args
 */
public static void main(String[] args)
{
    LocalAuthority localAuthority = new LocalAuthority();       
    URI serviceURI = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());
    SERVICE_ID = serviceURI.toString();
```

---

In file 
cdp/cadc-cert-gen/src/main/java/ca/nrc/cadc/cert/AbstractCertGenAction.java
The string CRED_SERVICE_ID should be configurable.
Proposed patch:
add a constructor where initialize the string. Not clear to me if the initialization should be added in init() method also.

  //public static final URI CRED_SERVICE_ID = URI.create("ivo://cadc.nrc.ca/cred");
    public static URI CRED_SERVICE_ID;

```
protected int expiring;
protected String userid;

public AbstractCertGenAction() {

    LocalAuthority localAuthority = new LocalAuthority();       
    CRED_SERVICE_ID = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());

}


public boolean init(final ArgumentMap argMap) throws IOException
{
    LocalAuthority localAuthority = new LocalAuthority();       
    CRED_SERVICE_ID = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());
```

**Comment by pdowler** [comment]
LocalAuthority is a mechanism for configuring a suite of services to find the "local" A&A services. It is not appropriate in the cadc-cdp Main method. We don't want a command-line client to depend on that config file and we would want to support usage like:

# delegate my cert to CADC
cadc-cdp -v --resourceID=ivo://cadc.nrc.ca/cred ...

# delegate my cert to INAF
cadc-cdp -v --resourceID=ivo://inaf.oats.it/cred ...

The right solution is to add support for a mandatory --resourceID argument. I think the same applies to cadc-cert-gen even though it is a data centre admin tool and not a normal client.

**Comment by pdowler** [comment]
added --resourceID command-line argument
